import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () =>  {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main>
        <div></div>
      </main>
    </div>
  )
}

export default Home
