import Head from "next/head";
import type { NextPage } from "next";
import Todo from "./todo";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Todo />
    </div>
  );
};

export default Home;
